# Generated by Django 3.0.6 on 2020-05-12 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todolist", "0003_auto_20200512_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="User",),
    ]
