# Generated by Django 3.0.6 on 2020-05-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0005_auto_20200512_1711"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="task_list", new_name="belongs_to",
        ),
    ]
